import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto('http://localhost:5173');
await page.waitForTimeout(5000);
await page.locator('button[title*="19.09s"]').first().click();
await page.waitForTimeout(500);
await page.locator('summary', { hasText: 'All attributes' }).click();
await page.waitForTimeout(300);
const panel = page.locator('div.w-\\[30rem\\]');
await panel.screenshot({ path: '/Users/andre/projects/opencode-otel-observability/.tmp/screenshot_detail2.png' });
await browser.close();
